var GAME_LEVELS = [
  ["                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                      x   k   y oooooooooooo    y     x                                                 ",
   "                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                ",
   "            x oooo           k x                                                                                       ",
   "            xxxxxxx!!!!!!xxxxxxx                                                                                       ",
   "            xxxxxxxxxxxxxxxxxxxx                                       x oooo          k  x                           x",
   "                                   xooo   k x                          xxxxxxxx!!!!!xxxxxxx                           x",
   "                                   xxxxxxxxxx                          xxxxxxxxxxxxxxxxxxxx                           x",
   "                                                                                                                      x",
   "                                                x   k  x                                              oooo            x",
   "  xx                    ooooo            y      xxxxxxxx                                  x!!!!!!!!xxxxxxxxxx         x",
   "  x                                                                                       xxxxxxxxxxxxxxxxxxx         x",
   "  x                  xxxxxxxxxx                                                                                       x",
   "  x                                    xxxxx                                                                          x",
   "  x  @                      oooooo   xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx                                 x",
   "  xxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx",
   "                xx!!!!!!xx                xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx",
   "                xx!!!!!!xx                xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                xx!!!!!!xx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                 xxxxxxxx                                                                                              ",
   "                                                                                                                       ",
   "                                                                                                                       "],
  ["                                                                                                                                                  ",
   "                                                                                                                                                  ",
   "                                                                                                                                                  ",
   "                                                                                                                                                  ",
   "               ooooooo                 o              oooooo                                                                                      ",
   "                                                                                                                                                  ",
   "         xxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxx!!!!!!!!!xxxxxxxxxxxx                                                                                    ",
   "                             xxxxxxxxx  xxxxxxxxxxx                   oo                             oooooo                                       ",
   "oo                                                                                                                                                ",
   "xxxx                                                                xxxxxxx!!!!!!xxxxxxx          xxxxxxxxxxxx                                    ",
   "                                                                          xxxxxxxx                                       ooooo                    ",
   "                                                                                                                                                  ",
   "!!!!!!xxxxxxx       ooooooo                                                                                   x!!!!!!!xxxxxxxxxx                  ",
   "xxxxxxx                                                x!!!!!!!!!!!!!!!!x                                     xxxxxxxxx                     ooooo ",
   "                 xxxxxxxxxxxx                          xxxxxxxxxxxxxxxxxx                                                                         ",
   " ooooooo                                                                                                                                 xxxxxxxxx",
   "xxxxxxxxxxx        oo                                                                                                                             ",
   "x                                                                                                                                                 ",
   "x                xxxxxxxx                      o                                                                           oooo                   ",
   "x                                                            oooo                                                                                 ",
   "x                             xxxxx!!!!!!!!!xxxxxxx                                                                   xxxxxxxxxxxxxxx!!!!!!!!!!!!!",
   "x                                 xxxxxxxxxxx                                                                                       xxxxxxxxxxxxxx",
   "x                                                        xxxxxxxxxxxxx                                     oooooooo                               ",
   "x                                              ooo                                                                                               x",
   "x                                                                                                    xxxxxxxxxxxxxxxxxxxx                        x",
   "x                oooo           xxxxxx!!!!!!!xxxxxxx                                                                                             x",
   "x                                    xxxxxxxxx                                                                                  oooooo           x",
   "x             xxxxxxxxxxx                                                                                                                        x",
   "x  @                                                                                                                                             x",
   "xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
